GoodZoo/Controllers/AnimalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GoodZoo.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GoodZoo.Controllers
{
    public class AnimalsController : Controller
    {
        public IAnimalRepository animalRepo;  // New!
        public GoodZooContext db = new GoodZooContext();
        public AnimalsController(IAnimalRepository repo = null)
        {
            if (repo == null)
            {
                this.animalRepo = new EFAnimalRepository();
            }
            else
            {
                this.animalRepo = repo;
            }
        }

        public ViewResult Index()
        {
            // Updated:
            return View(animalRepo.Animals.Include(animals => animals.Vet).ToList());
        }

        public IActionResult Details(int id)
        {
            // Updated:
            
            Animal thisAnimal = animalRepo.Animals.FirstOrDefault(x => x.AnimalId == id);
            return View(thisAnimal);
        }

        public IActionResult Create()
        {
            ViewBag.VetId = new SelectList(db.Vets, "VetId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Animal animal)
        {
            animalRepo.Save(animal);   // Updated
            // Removed db.SaveChanges() call
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            // Updated:
            ViewBag.VetId = new SelectList(db.Vets, "VetId", "Name");
            Animal thisAnimal = animalRepo.Animals.FirstOrDefault(x => x.AnimalId == id);
            return View(thisAnimal);
        }

        [HttpPost]
        public IActionResult Edit(Animal animal)
        {
            animalRepo.Edit(animal);   // Updated!
            // Removed db.SaveChanges() call
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            // Updated:
            Animal thisAnimal = animalRepo.Animals.FirstOrDefault(x => x.AnimalId == id);
            return View(thisAnimal);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            // Updated:
            Animal thisAnimal = animalRepo.Animals.FirstOrDefault(x => x.AnimalId == id);
            animalRepo.Remove(thisAnimal);   // Updated!
            // Removed db.SaveChanges() call
            return RedirectToAction("Index");
        }
    }
}

GoodZoo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace GoodZoo.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

GoodZoo/Controllers/VetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GoodZoo.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace GoodZoo.Controllers
{
    public class VetsController : Controller
    {
        private IVetRepository animalRepo;  // New!
        private GoodZooContext db = new GoodZooContext();
        public VetsController(IVetRepository repo = null)
        {
            if (repo == null)
            {
                this.animalRepo = new EFVetRepository();
            }
            else
            {
                this.animalRepo = repo;
            }
        }

        public ViewResult Index()
        {
            List<Vet> model = animalRepo.Vets.ToList();
            return View(model);
        }

        public IActionResult Details(int id)
        {
            // Updated:
            Vet thisVet = animalRepo.Vets.FirstOrDefault(x => x.VetId == id);
            return View(thisVet);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Vet vet)
        {
            animalRepo.Save(vet);   // Updated
            // Removed db.SaveChanges() call
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            // Updated:
            Vet thisVet = animalRepo.Vets.FirstOrDefault(x => x.VetId == id);
            return View(thisVet);
        }

        [HttpPost]
        public IActionResult Edit(Vet vet)
        {
            animalRepo.Edit(vet);   // Updated!
            // Removed db.SaveChanges() call
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            // Updated:
            Vet thisVet = animalRepo.Vets.FirstOrDefault(x => x.VetId == id);
            return View(thisVet);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            // Updated:
            Vet thisVet = animalRepo.Vets.FirstOrDefault(x => x.VetId == id);
            animalRepo.Remove(thisVet);   // Updated!
            // Removed db.SaveChanges() call
            return RedirectToAction("Index");
        }
    }
}

GoodZoo/Views/Home/Index.cshtml
@model IEnumerable<GoodZoo.Models.Animal>

@{
    ViewData["Title"] = "GoodZoo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<html>
<head>
    <title>GoodZoo</title>
</head>
<body>
    <h2>a good place to call home</h2>
    <p>@Html.ActionLink("View Animal Index", "Index", "Animals")</p>
    <p>@Html.ActionLink("View Zookeeper Index", "Index", "Vets")</p>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="~/images/gorilla.jpg" alt="gorilla" style="width:100%;">
            </div>

            <div class="item">
                <img src="~/images/hippo.jpg" alt="hippo" style="width:100%;">
            </div>

            <div class="item">
                <img src="ny.jpg" alt="New york" style="width:100%;">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    </div>
</body>
</html>